VERSION="2.5.0"

[DOCUMENTATION]
ORG_NAME="Stellar Meme Dot Fun"
ORG_URL="https://stellarmeme.fun"
ORG_LOGO="https://stellarmeme.fun/assets/funstellarmeme-web-logo.png"
ORG_DESCRIPTION="StellarMeme is not just another meme tokenâ€”itâ€™s a collectible, a keepsake, and a part of the fun! Whether youâ€™re here for the hype, the humor, or the long-term value, this token is designed to bring joy while riding the waves of the Stellar blockchain. Cute, unique, and full of potentialâ€”because why just pump when you can also keep the fun forever?"

[[CURRENCIES]]
code="FATPANDA"
issuer="GCQ4A4J24YLGRYBFBIAYNNUV6OGWHTL4UL7B3U2SHKUBWKXWH6HFLABI"
status="live"
display_decimals=5
name="FATPANDA"
fixed_number=35000000000
desc="FATPANDA is more than just a tokenâ€”it's a symbol of fun, community, and pure panda power! ğŸ¼ğŸ’° Whether you're here for the memes, the vibes, or just love the chunky panda spirit, FATPANDA is built to bring joy and a little extra weight to your portfolio. Pump, fun, and a keepsakeâ€”because who doesnâ€™t love a fat, happy panda?"
conditions="Maximum supply of FATPANDA is 35B tokens only"
image="https://stellarmeme.fun/assets/FATPANDA.png"

[[CURRENCIES]]
code="DONX"
issuer="GAJU2IJO4NYX7BRHFXBX5CQZG7YQTIKWM6DVSVGGJ2UZHY363KRCHHOF"
status="live"
display_decimals=5
name="DONX"
fixed_number=35000000000
desc="DONX isnâ€™t just another meme tokenâ€”itâ€™s a movement! Inspired by fun, fueled by community, and built on the Stellar blockchain for speed, efficiency, and decentralization. Whether you're here for the pump, the fun, or the keepsake, DONX is designed to be a token youâ€™ll remember. Because memes arenâ€™t just jokes, theyâ€™re the future! ğŸŒŸğŸ”¥"
conditions="Maximum supply of DONX is 35B tokens only"
image="https://stellarmeme.fun/assets/DONX.png"

[[CURRENCIES]]
code="FOXY"
issuer="GAMRIOQZL2VM2JIHXPH4SHUG245X2FWGHV3DY63ZLGKKORTVQMNUBOXY"
status="live"
display_decimals=5
name="FOXY"
fixed_number=35000000000
desc="Whether you're a trader, collector, or just love the thrill of the market, FOXY is your dynamic token in the Stellar ecosystem. Agile, intelligent, and built for excitementâ€”FOXY isnâ€™t just a token, itâ€™s an experience.ğŸš€ Stay sharp, stay fast, stay FOXY!ğŸ’¨"
conditions="Maximum supply of FOXY is 35B tokens only"
image="https://stellarmeme.fun/assets/FOXY.png"
